load("@d2l_rules_csharp//csharp/private:rules/imports.bzl", "import_multiframework_library")

import_multiframework_library(
    name = "Accessibility",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Accessibility",
)

import_multiframework_library(
    name = "CustomMarshalers",
    visibility = ["//visibility:public"],

    net472 = "@net472//:CustomMarshalers",
)

import_multiframework_library(
    name = "ISymWrapper",
    visibility = ["//visibility:public"],

    net472 = "@net472//:ISymWrapper",
)

import_multiframework_library(
    name = "Microsoft.Activities.Build",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.Activities.Build",
)

import_multiframework_library(
    name = "Microsoft.Build",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.Build",
)

import_multiframework_library(
    name = "Microsoft.Build.Conversion.v4.0",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.Build.Conversion.v4.0",
)

import_multiframework_library(
    name = "Microsoft.Build.Engine",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.Build.Engine",
)

import_multiframework_library(
    name = "Microsoft.Build.Framework",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.Build.Framework",
)

import_multiframework_library(
    name = "Microsoft.Build.Tasks.v4.0",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.Build.Tasks.v4.0",
)

import_multiframework_library(
    name = "Microsoft.Build.Utilities.v4.0",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.Build.Utilities.v4.0",
)

import_multiframework_library(
    name = "Microsoft.CSharp",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.CSharp",
)

import_multiframework_library(
    name = "Microsoft.JScript",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.JScript",
)

import_multiframework_library(
    name = "Microsoft.VisualBasic",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.VisualBasic",
)

import_multiframework_library(
    name = "Microsoft.VisualBasic.Compatibility",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.VisualBasic.Compatibility",
)

import_multiframework_library(
    name = "Microsoft.VisualBasic.Compatibility.Data",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.VisualBasic.Compatibility.Data",
)

import_multiframework_library(
    name = "Microsoft.VisualC",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.VisualC",
)

import_multiframework_library(
    name = "Microsoft.VisualC.STLCLR",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.VisualC.STLCLR",
)

import_multiframework_library(
    name = "Microsoft.Win32.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:Microsoft.Win32.Primitives",
)

import_multiframework_library(
    name = "mscorlib",
    visibility = ["//visibility:public"],

    net472 = "@net472//:mscorlib",
)

import_multiframework_library(
    name = "netstandard",
    visibility = ["//visibility:public"],

    net472 = "@net472//:netstandard",
)

import_multiframework_library(
    name = "PresentationBuildTasks",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationBuildTasks",
)

import_multiframework_library(
    name = "PresentationCore",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationCore",
)

import_multiframework_library(
    name = "PresentationFramework",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationFramework",
)

import_multiframework_library(
    name = "PresentationFramework.Aero",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationFramework.Aero",
)

import_multiframework_library(
    name = "PresentationFramework.Aero2",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationFramework.Aero2",
)

import_multiframework_library(
    name = "PresentationFramework.AeroLite",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationFramework.AeroLite",
)

import_multiframework_library(
    name = "PresentationFramework.Classic",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationFramework.Classic",
)

import_multiframework_library(
    name = "PresentationFramework.Luna",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationFramework.Luna",
)

import_multiframework_library(
    name = "PresentationFramework.Royale",
    visibility = ["//visibility:public"],

    net472 = "@net472//:PresentationFramework.Royale",
)

import_multiframework_library(
    name = "ReachFramework",
    visibility = ["//visibility:public"],

    net472 = "@net472//:ReachFramework",
)

import_multiframework_library(
    name = "sysglobl",
    visibility = ["//visibility:public"],

    net472 = "@net472//:sysglobl",
)

import_multiframework_library(
    name = "System",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System",
)

import_multiframework_library(
    name = "System.Activities",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Activities",
)

import_multiframework_library(
    name = "System.Activities.Core.Presentation",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Activities.Core.Presentation",
)

import_multiframework_library(
    name = "System.Activities.DurableInstancing",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Activities.DurableInstancing",
)

import_multiframework_library(
    name = "System.Activities.Presentation",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Activities.Presentation",
)

import_multiframework_library(
    name = "System.AddIn",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.AddIn",
)

import_multiframework_library(
    name = "System.AddIn.Contract",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.AddIn.Contract",
)

import_multiframework_library(
    name = "System.AppContext",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.AppContext",
)

import_multiframework_library(
    name = "System.Collections",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Collections",
)

import_multiframework_library(
    name = "System.Collections.Concurrent",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Collections.Concurrent",
)

import_multiframework_library(
    name = "System.Collections.NonGeneric",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Collections.NonGeneric",
)

import_multiframework_library(
    name = "System.Collections.Specialized",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Collections.Specialized",
)

import_multiframework_library(
    name = "System.ComponentModel",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ComponentModel",
)

import_multiframework_library(
    name = "System.ComponentModel.Annotations",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ComponentModel.Annotations",
)

import_multiframework_library(
    name = "System.ComponentModel.Composition",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ComponentModel.Composition",
)

import_multiframework_library(
    name = "System.ComponentModel.Composition.Registration",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ComponentModel.Composition.Registration",
)

import_multiframework_library(
    name = "System.ComponentModel.DataAnnotations",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ComponentModel.DataAnnotations",
)

import_multiframework_library(
    name = "System.ComponentModel.EventBasedAsync",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ComponentModel.EventBasedAsync",
)

import_multiframework_library(
    name = "System.ComponentModel.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ComponentModel.Primitives",
)

import_multiframework_library(
    name = "System.ComponentModel.TypeConverter",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ComponentModel.TypeConverter",
)

import_multiframework_library(
    name = "System.Configuration",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Configuration",
)

import_multiframework_library(
    name = "System.Configuration.Install",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Configuration.Install",
)

import_multiframework_library(
    name = "System.Console",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Console",
)

import_multiframework_library(
    name = "System.Core",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Core",
)

import_multiframework_library(
    name = "System.Data",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data",
)

import_multiframework_library(
    name = "System.Data.Common",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.Common",
)

import_multiframework_library(
    name = "System.Data.DataSetExtensions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.DataSetExtensions",
)

import_multiframework_library(
    name = "System.Data.Entity",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.Entity",
)

import_multiframework_library(
    name = "System.Data.Entity.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.Entity.Design",
)

import_multiframework_library(
    name = "System.Data.Linq",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.Linq",
)

import_multiframework_library(
    name = "System.Data.OracleClient",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.OracleClient",
)

import_multiframework_library(
    name = "System.Data.Services",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.Services",
)

import_multiframework_library(
    name = "System.Data.Services.Client",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.Services.Client",
)

import_multiframework_library(
    name = "System.Data.Services.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.Services.Design",
)

import_multiframework_library(
    name = "System.Data.SqlXml",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Data.SqlXml",
)

import_multiframework_library(
    name = "System.Deployment",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Deployment",
)

import_multiframework_library(
    name = "System.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Design",
)

import_multiframework_library(
    name = "System.Device",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Device",
)

import_multiframework_library(
    name = "System.Diagnostics.Contracts",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.Contracts",
)

import_multiframework_library(
    name = "System.Diagnostics.Debug",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.Debug",
)

import_multiframework_library(
    name = "System.Diagnostics.FileVersionInfo",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.FileVersionInfo",
)

import_multiframework_library(
    name = "System.Diagnostics.Process",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.Process",
)

import_multiframework_library(
    name = "System.Diagnostics.StackTrace",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.StackTrace",
)

import_multiframework_library(
    name = "System.Diagnostics.TextWriterTraceListener",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.TextWriterTraceListener",
)

import_multiframework_library(
    name = "System.Diagnostics.Tools",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.Tools",
)

import_multiframework_library(
    name = "System.Diagnostics.TraceSource",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.TraceSource",
)

import_multiframework_library(
    name = "System.Diagnostics.Tracing",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Diagnostics.Tracing",
)

import_multiframework_library(
    name = "System.DirectoryServices",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.DirectoryServices",
)

import_multiframework_library(
    name = "System.DirectoryServices.AccountManagement",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.DirectoryServices.AccountManagement",
)

import_multiframework_library(
    name = "System.DirectoryServices.Protocols",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.DirectoryServices.Protocols",
)

import_multiframework_library(
    name = "System.Drawing",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Drawing",
)

import_multiframework_library(
    name = "System.Drawing.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Drawing.Design",
)

import_multiframework_library(
    name = "System.Drawing.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Drawing.Primitives",
)

import_multiframework_library(
    name = "System.Dynamic",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Dynamic",
)

import_multiframework_library(
    name = "System.Dynamic.Runtime",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Dynamic.Runtime",
)

import_multiframework_library(
    name = "System.EnterpriseServices",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.EnterpriseServices",
)

import_multiframework_library(
    name = "System.EnterpriseServices.Thunk",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.EnterpriseServices.Thunk",
)

import_multiframework_library(
    name = "System.Globalization",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Globalization",
)

import_multiframework_library(
    name = "System.Globalization.Calendars",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Globalization.Calendars",
)

import_multiframework_library(
    name = "System.Globalization.Extensions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Globalization.Extensions",
)

import_multiframework_library(
    name = "System.IdentityModel",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IdentityModel",
)

import_multiframework_library(
    name = "System.IdentityModel.Selectors",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IdentityModel.Selectors",
)

import_multiframework_library(
    name = "System.IdentityModel.Services",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IdentityModel.Services",
)

import_multiframework_library(
    name = "System.IO",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO",
)

import_multiframework_library(
    name = "System.IO.Compression",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.Compression",
)

import_multiframework_library(
    name = "System.IO.Compression.FileSystem",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.Compression.FileSystem",
)

import_multiframework_library(
    name = "System.IO.Compression.ZipFile",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.Compression.ZipFile",
)

import_multiframework_library(
    name = "System.IO.FileSystem",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.FileSystem",
)

import_multiframework_library(
    name = "System.IO.FileSystem.DriveInfo",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.FileSystem.DriveInfo",
)

import_multiframework_library(
    name = "System.IO.FileSystem.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.FileSystem.Primitives",
)

import_multiframework_library(
    name = "System.IO.FileSystem.Watcher",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.FileSystem.Watcher",
)

import_multiframework_library(
    name = "System.IO.IsolatedStorage",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.IsolatedStorage",
)

import_multiframework_library(
    name = "System.IO.Log",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.Log",
)

import_multiframework_library(
    name = "System.IO.MemoryMappedFiles",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.MemoryMappedFiles",
)

import_multiframework_library(
    name = "System.IO.Pipes",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.Pipes",
)

import_multiframework_library(
    name = "System.IO.UnmanagedMemoryStream",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.IO.UnmanagedMemoryStream",
)

import_multiframework_library(
    name = "System.Linq",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Linq",
)

import_multiframework_library(
    name = "System.Linq.Expressions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Linq.Expressions",
)

import_multiframework_library(
    name = "System.Linq.Parallel",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Linq.Parallel",
)

import_multiframework_library(
    name = "System.Linq.Queryable",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Linq.Queryable",
)

import_multiframework_library(
    name = "System.Management",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Management",
)

import_multiframework_library(
    name = "System.Management.Instrumentation",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Management.Instrumentation",
)

import_multiframework_library(
    name = "System.Messaging",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Messaging",
)

import_multiframework_library(
    name = "System.Net",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net",
)

import_multiframework_library(
    name = "System.Net.Http",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.Http",
)

import_multiframework_library(
    name = "System.Net.Http.Rtc",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.Http.Rtc",
)

import_multiframework_library(
    name = "System.Net.Http.WebRequest",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.Http.WebRequest",
)

import_multiframework_library(
    name = "System.Net.NameResolution",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.NameResolution",
)

import_multiframework_library(
    name = "System.Net.NetworkInformation",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.NetworkInformation",
)

import_multiframework_library(
    name = "System.Net.Ping",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.Ping",
)

import_multiframework_library(
    name = "System.Net.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.Primitives",
)

import_multiframework_library(
    name = "System.Net.Requests",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.Requests",
)

import_multiframework_library(
    name = "System.Net.Security",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.Security",
)

import_multiframework_library(
    name = "System.Net.Sockets",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.Sockets",
)

import_multiframework_library(
    name = "System.Net.WebHeaderCollection",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.WebHeaderCollection",
)

import_multiframework_library(
    name = "System.Net.WebSockets",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.WebSockets",
)

import_multiframework_library(
    name = "System.Net.WebSockets.Client",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Net.WebSockets.Client",
)

import_multiframework_library(
    name = "System.Numerics",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Numerics",
)

import_multiframework_library(
    name = "System.ObjectModel",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ObjectModel",
)

import_multiframework_library(
    name = "System.Printing",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Printing",
)

import_multiframework_library(
    name = "System.Reflection",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Reflection",
)

import_multiframework_library(
    name = "System.Reflection.Context",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Reflection.Context",
)

import_multiframework_library(
    name = "System.Reflection.Emit",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Reflection.Emit",
)

import_multiframework_library(
    name = "System.Reflection.Emit.ILGeneration",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Reflection.Emit.ILGeneration",
)

import_multiframework_library(
    name = "System.Reflection.Emit.Lightweight",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Reflection.Emit.Lightweight",
)

import_multiframework_library(
    name = "System.Reflection.Extensions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Reflection.Extensions",
)

import_multiframework_library(
    name = "System.Reflection.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Reflection.Primitives",
)

import_multiframework_library(
    name = "System.Resources.Reader",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Resources.Reader",
)

import_multiframework_library(
    name = "System.Resources.ResourceManager",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Resources.ResourceManager",
)

import_multiframework_library(
    name = "System.Resources.Writer",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Resources.Writer",
)

import_multiframework_library(
    name = "System.Runtime",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime",
)

import_multiframework_library(
    name = "System.Runtime.Caching",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Caching",
)

import_multiframework_library(
    name = "System.Runtime.CompilerServices.VisualC",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.CompilerServices.VisualC",
)

import_multiframework_library(
    name = "System.Runtime.DurableInstancing",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.DurableInstancing",
)

import_multiframework_library(
    name = "System.Runtime.Extensions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Extensions",
)

import_multiframework_library(
    name = "System.Runtime.Handles",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Handles",
)

import_multiframework_library(
    name = "System.Runtime.InteropServices",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.InteropServices",
)

import_multiframework_library(
    name = "System.Runtime.InteropServices.RuntimeInformation",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.InteropServices.RuntimeInformation",
)

import_multiframework_library(
    name = "System.Runtime.InteropServices.WindowsRuntime",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.InteropServices.WindowsRuntime",
)

import_multiframework_library(
    name = "System.Runtime.Numerics",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Numerics",
)

import_multiframework_library(
    name = "System.Runtime.Remoting",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Remoting",
)

import_multiframework_library(
    name = "System.Runtime.Serialization",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Serialization",
)

import_multiframework_library(
    name = "System.Runtime.Serialization.Formatters",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Serialization.Formatters",
)

import_multiframework_library(
    name = "System.Runtime.Serialization.Formatters.Soap",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Serialization.Formatters.Soap",
)

import_multiframework_library(
    name = "System.Runtime.Serialization.Json",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Serialization.Json",
)

import_multiframework_library(
    name = "System.Runtime.Serialization.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Serialization.Primitives",
)

import_multiframework_library(
    name = "System.Runtime.Serialization.Xml",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Runtime.Serialization.Xml",
)

import_multiframework_library(
    name = "System.Security",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security",
)

import_multiframework_library(
    name = "System.Security.Claims",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security.Claims",
)

import_multiframework_library(
    name = "System.Security.Cryptography.Algorithms",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security.Cryptography.Algorithms",
)

import_multiframework_library(
    name = "System.Security.Cryptography.Csp",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security.Cryptography.Csp",
)

import_multiframework_library(
    name = "System.Security.Cryptography.Encoding",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security.Cryptography.Encoding",
)

import_multiframework_library(
    name = "System.Security.Cryptography.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security.Cryptography.Primitives",
)

import_multiframework_library(
    name = "System.Security.Cryptography.X509Certificates",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security.Cryptography.X509Certificates",
)

import_multiframework_library(
    name = "System.Security.Principal",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security.Principal",
)

import_multiframework_library(
    name = "System.Security.SecureString",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Security.SecureString",
)

import_multiframework_library(
    name = "System.ServiceModel",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel",
)

import_multiframework_library(
    name = "System.ServiceModel.Activation",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Activation",
)

import_multiframework_library(
    name = "System.ServiceModel.Activities",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Activities",
)

import_multiframework_library(
    name = "System.ServiceModel.Channels",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Channels",
)

import_multiframework_library(
    name = "System.ServiceModel.Discovery",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Discovery",
)

import_multiframework_library(
    name = "System.ServiceModel.Duplex",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Duplex",
)

import_multiframework_library(
    name = "System.ServiceModel.Http",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Http",
)

import_multiframework_library(
    name = "System.ServiceModel.NetTcp",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.NetTcp",
)

import_multiframework_library(
    name = "System.ServiceModel.Primitives",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Primitives",
)

import_multiframework_library(
    name = "System.ServiceModel.Routing",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Routing",
)

import_multiframework_library(
    name = "System.ServiceModel.Security",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Security",
)

import_multiframework_library(
    name = "System.ServiceModel.Web",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceModel.Web",
)

import_multiframework_library(
    name = "System.ServiceProcess",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ServiceProcess",
)

import_multiframework_library(
    name = "System.Speech",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Speech",
)

import_multiframework_library(
    name = "System.Text.Encoding",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Text.Encoding",
)

import_multiframework_library(
    name = "System.Text.Encoding.Extensions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Text.Encoding.Extensions",
)

import_multiframework_library(
    name = "System.Text.RegularExpressions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Text.RegularExpressions",
)

import_multiframework_library(
    name = "System.Threading",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Threading",
)

import_multiframework_library(
    name = "System.Threading.Overlapped",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Threading.Overlapped",
)

import_multiframework_library(
    name = "System.Threading.Tasks",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Threading.Tasks",
)

import_multiframework_library(
    name = "System.Threading.Tasks.Parallel",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Threading.Tasks.Parallel",
)

import_multiframework_library(
    name = "System.Threading.Thread",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Threading.Thread",
)

import_multiframework_library(
    name = "System.Threading.ThreadPool",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Threading.ThreadPool",
)

import_multiframework_library(
    name = "System.Threading.Timer",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Threading.Timer",
)

import_multiframework_library(
    name = "System.Transactions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Transactions",
)

import_multiframework_library(
    name = "System.ValueTuple",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.ValueTuple",
)

import_multiframework_library(
    name = "System.Web",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web",
)

import_multiframework_library(
    name = "System.Web.Abstractions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.Abstractions",
)

import_multiframework_library(
    name = "System.Web.ApplicationServices",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.ApplicationServices",
)

import_multiframework_library(
    name = "System.Web.DataVisualization",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.DataVisualization",
)

import_multiframework_library(
    name = "System.Web.DataVisualization.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.DataVisualization.Design",
)

import_multiframework_library(
    name = "System.Web.DynamicData",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.DynamicData",
)

import_multiframework_library(
    name = "System.Web.DynamicData.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.DynamicData.Design",
)

import_multiframework_library(
    name = "System.Web.Entity",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.Entity",
)

import_multiframework_library(
    name = "System.Web.Entity.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.Entity.Design",
)

import_multiframework_library(
    name = "System.Web.Extensions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.Extensions",
)

import_multiframework_library(
    name = "System.Web.Extensions.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.Extensions.Design",
)

import_multiframework_library(
    name = "System.Web.Mobile",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.Mobile",
)

import_multiframework_library(
    name = "System.Web.RegularExpressions",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.RegularExpressions",
)

import_multiframework_library(
    name = "System.Web.Routing",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.Routing",
)

import_multiframework_library(
    name = "System.Web.Services",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Web.Services",
)

import_multiframework_library(
    name = "System.Windows",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Windows",
)

import_multiframework_library(
    name = "System.Windows.Controls.Ribbon",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Windows.Controls.Ribbon",
)

import_multiframework_library(
    name = "System.Windows.Forms",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Windows.Forms",
)

import_multiframework_library(
    name = "System.Windows.Forms.DataVisualization",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Windows.Forms.DataVisualization",
)

import_multiframework_library(
    name = "System.Windows.Forms.DataVisualization.Design",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Windows.Forms.DataVisualization.Design",
)

import_multiframework_library(
    name = "System.Windows.Input.Manipulations",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Windows.Input.Manipulations",
)

import_multiframework_library(
    name = "System.Windows.Presentation",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Windows.Presentation",
)

import_multiframework_library(
    name = "System.Workflow.Activities",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Workflow.Activities",
)

import_multiframework_library(
    name = "System.Workflow.ComponentModel",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Workflow.ComponentModel",
)

import_multiframework_library(
    name = "System.Workflow.Runtime",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Workflow.Runtime",
)

import_multiframework_library(
    name = "System.WorkflowServices",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.WorkflowServices",
)

import_multiframework_library(
    name = "System.Xaml",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xaml",
)

import_multiframework_library(
    name = "System.Xml",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml",
)

import_multiframework_library(
    name = "System.Xml.Linq",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml.Linq",
)

import_multiframework_library(
    name = "System.Xml.ReaderWriter",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml.ReaderWriter",
)

import_multiframework_library(
    name = "System.Xml.Serialization",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml.Serialization",
)

import_multiframework_library(
    name = "System.Xml.XDocument",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml.XDocument",
)

import_multiframework_library(
    name = "System.Xml.XmlDocument",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml.XmlDocument",
)

import_multiframework_library(
    name = "System.Xml.XmlSerializer",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml.XmlSerializer",
)

import_multiframework_library(
    name = "System.Xml.XPath",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml.XPath",
)

import_multiframework_library(
    name = "System.Xml.XPath.XDocument",
    visibility = ["//visibility:public"],

    net472 = "@net472//:System.Xml.XPath.XDocument",
)

import_multiframework_library(
    name = "UIAutomationClient",
    visibility = ["//visibility:public"],

    net472 = "@net472//:UIAutomationClient",
)

import_multiframework_library(
    name = "UIAutomationClientsideProviders",
    visibility = ["//visibility:public"],

    net472 = "@net472//:UIAutomationClientsideProviders",
)

import_multiframework_library(
    name = "UIAutomationProvider",
    visibility = ["//visibility:public"],

    net472 = "@net472//:UIAutomationProvider",
)

import_multiframework_library(
    name = "UIAutomationTypes",
    visibility = ["//visibility:public"],

    net472 = "@net472//:UIAutomationTypes",
)

import_multiframework_library(
    name = "WindowsBase",
    visibility = ["//visibility:public"],

    net472 = "@net472//:WindowsBase",
)

import_multiframework_library(
    name = "WindowsFormsIntegration",
    visibility = ["//visibility:public"],

    net472 = "@net472//:WindowsFormsIntegration",
)

import_multiframework_library(
    name = "XamlBuildTask",
    visibility = ["//visibility:public"],

    net472 = "@net472//:XamlBuildTask",
)
