load(
    "@d2l_rules_csharp//csharp:defs.bzl",
    "csharp_library",
)

csharp_library(
    name = "net20",
    target_frameworks = ["net20"],
)

csharp_library(
    name = "net40",
    target_frameworks = ["net40"],
)

csharp_library(
    name = "net45",
    target_frameworks = ["net45"],
)

csharp_library(
    name = "net451",
    target_frameworks = ["net451"],
)

csharp_library(
    name = "net452",
    target_frameworks = ["net452"],
)

csharp_library(
    name = "net46",
    target_frameworks = ["net46"],
)

csharp_library(
    name = "net461",
    target_frameworks = ["net461"],
)

csharp_library(
    name = "net462",
    target_frameworks = ["net462"],
)

csharp_library(
    name = "net47",
    target_frameworks = ["net47"],
)

csharp_library(
    name = "net471",
    target_frameworks = ["net471"],
)

csharp_library(
    name = "net472",
    target_frameworks = ["net472"],
)

csharp_library(
    name = "net48",
    target_frameworks = ["net48"],
)

csharp_library(
    name = "netcoreapp2.1",
    target_frameworks = ["netcoreapp2.1"],
)

csharp_library(
    name = "netcoreapp2.2",
    target_frameworks = ["netcoreapp2.2"],
)

csharp_library(
    name = "netcoreapp3.0",
    target_frameworks = ["netcoreapp3.0"],
)

csharp_library(
    name = "netstandard2.0",
    target_frameworks = ["netstandard2.0"],
)

csharp_library(
    name = "netstandard2.1",
    target_frameworks = ["netstandard2.1"],
)
