name: CI
on: pull_request

jobs:
  build:
    name: Build examples
    runs-on: ubuntu-latest
    container:
      image: gcr.io/cloud-marketplace-containers/google/bazel:0.29.1
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Dump the action graph
        run: cd examples && bazel aquery 'deps(...)'
